### ISSUE TITLE
Injecting auto_prev usage results in downstream AutoFilter not called

### ISSUE THREAD

**Issue by jdonald** [leapmotion/autowiring#736] opened 2015-09-01 21:04 UTC
This problem was first discovered 27 days ago in http://sf-github.leap.corp/leapmotion/platform/issues/2602

We have spent time debugging it and still don't understand the mechanism. Perhaps this is due to some interaction between auto_prev and auto_out accumulated arguments e.g. <tt>const FigureSubFrame* frames[]</tt>.

We can verify that Figure3D::AutoFilter is called in normal operation, but then the entire AutoFilter function stops getting entered as soon as the 'p' key is pressed in Figure. This happens if and only if an AutoFilter using auto_prev is injected. For example, the problem can be reproduced via HandOpticalFlow :

    LeapSvc.exe --run --tracking_version=v2_init

but when the <tt>AutoRequired\<HandOpticalFlow>()</tt> is removed, the pause/unpause problem goes away.

This applies to injecting HandOpticalFlow, HandOpticalFlowDebug, or HandDepthEstimate all of which use auto_prev. With V3 tracking, many of these classes have become necessary, making this issue more of a concern.

**Comment by jnguyen75** [comment] 2015-09-01 21:15
Ah hah.. good catch

**Comment by jdonald** [comment] 2015-09-28 21:03
I have tested with `--tracking_version={v3_exp,v2}` and can confirm this is fixed on the tip of autowiring develop. w00t

v3_alpha can't pause, but I think that's due to some other workaround in platform.

**Comment by jdonald** [comment] 2015-09-28 21:25
I have confirmed this working with v3_alpha upon reverting the pause-disabling workaround and also reverting the timestamp code that necessitated the workaround. Closing here, although it will take more effort to close the corresponding platform issue.

**Comment by jdonald** [comment] 2015-09-28 21:49
Come to think of it, is the proper etiquette to keep this open and add it to the 0.7.4 milestone, then something will match it up when 0.7.4 gets released?

**Comment by codemercenary** [comment] 2015-09-28 21:55
Nope, the bug has been confirmed as closed, we add the milestone and close the issue.  If it stays open it looks like it still needs work.

**Closed** 2015-09-28 22:08 UTC
Labels: bug
