### ISSUE TITLE
Adding an AutoFilter lambda to a packet while being processing results in being called twice

### ISSUE THREAD

**Issue by veronicaz41** [leapmotion/autowiring#829] opened 2015-12-01 19:20 UTC
There appears to be a race condition in Autowiring where adding an AutoFilter
lambda to a packet while it is processing may result in it being called twice.

This problem happens in Platform (See PR #4044).

**Comment by codemercenary** [comment] 2015-12-02 13:50
I believe this may be a duplicate of #704.

**Comment by codemercenary** [comment] 2016-04-11 14:46
This issue should be addressed already, I don't see it reported anymore.

**Comment by codemercenary** [comment] 2016-04-11 14:50
I think #866 may have addressed this one.

**Comment by codemercenary** [comment] 2016-04-11 14:50
Closing as duplicate.

**Closed by codemercenary** 2016-04-11 14:50 UTC
Labels: bug, duplicate
